### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by engineergamingistaking** [Patoke/re-plants-vs-zombies#4]
It says it can't find bass.dll, I have the Plants vs. Zombies game files, where do I put them?

**Comment by Patoke** [comment]
Hello, that is most likely because of re-plants-vs-zombies being built as x64 and the normal Plants vs. Zombies game files containing x86 binaries and causing a mismatch between the bass.dll re-plants-vs-zombies expects and the actual bass.dll.

Download the latest BASS version directly from their website [here](https://www.un4seen.com/download.php?bass24). (the x64 version of bass is located in the x64 folder inside the zip)

After that just drop ``bass.dll`` inside your game files and it should work fine.

We will make sure to, from now on, start statically linking the BASS library inside the project so such stuff doesn't happen anymore.

Best regards, Patoke.

**Comment by minerscale** [comment]
Hi! First of all clone this repo again since I just changed the history of it to include a bunch of commits in the history that got irreparably squashed. (this will never happen again this is a one time special).

As to your actual question, this repo uses the most up to date 64 bit build of un4seen developments bass. You can download it here: https://www.un4seen.com/download.php?bass24

The current build of the game does not support reading off the main.pak due to some 64 bit shenanigans with the way the library works, this is being worked on and the plan is to give the game the ability to read from pak files. For now you'll have to undergo the fairly completely undocumented and annoying process of building tools/decrypt.c and tools/metadata.c, running the decrypt binary you just built with the main.pak file in the same directory will decrypt it (really it's just xor'd with a bunch of numbers) and then run the metadata executable which will complain at you until you've given it the right directory structure for it to unpack the game files into. ONCE you've done that, you can try running the game with it then, but actually I think there's some weird encoding stuff going on.

Honestly I'll just send you a compressed main.pak with my changes already made. I've made a fair few to this directory to get it working (including fixing a couple mistakes they made with the original files!? I'll find a way to apply a patch with a diff soon: https://1drv.ms/u/s!AgAdDsqhqeAPhmrr2HRwvZ2dS12n?e=zoAmR7

Thanks for your patience with the munted build system and if you'd like to see it fixed we're always keen on pull requests.

- Aaron.

**Comment by engineergamingistaking** [comment]
> Hello, that is most likely because of re-plants-vs-zombies being built as x64 and the normal Plants vs. Zombies game files containing x86 binaries and causing a mismatch between the bass.dll re-plants-vs-zombies expects and the actual bass.dll.
> 
> Download the latest BASS version directly from their website [here](https://www.un4seen.com/download.php?bass24). (the x64 version of bass is located in the x64 folder inside the zip)
> 
> After that just drop `bass.dll` inside your game files and it should work fine.
> 
> We will make sure to, from now on, start statically linking the BASS library inside the project so such stuff doesn't happen anymore.
> 
> Best regards, Patoke.

Thanks, it worked!

**Comment by engineergamingistaking** [comment]
> Hi! First of all clone this repo again since I just changed the history of it to include a bunch of commits in the history that got irreparably squashed. (this will never happen again this is a one time special).
> 
> As to your actual question, this repo uses the most up to date 64 bit build of un4seen developments bass. You can download it here: https://www.un4seen.com/download.php?bass24
> 
> The current build of the game does not support reading off the main.pak due to some 64 bit shenanigans with the way the library works, this is being worked on and the plan is to give the game the ability to read from pak files. For now you'll have to undergo the fairly completely undocumented and annoying process of building tools/decrypt.c and tools/metadata.c, running the decrypt binary you just built with the main.pak file in the same directory will decrypt it (really it's just xor'd with a bunch of numbers) and then run the metadata executable which will complain at you until you've given it the right directory structure for it to unpack the game files into. ONCE you've done that, you can try running the game with it then, but actually I think there's some weird encoding stuff going on.
> 
> Honestly I'll just send you a compressed main.pak with my changes already made. I've made a fair few to this directory to get it working (including fixing a couple mistakes they made with the original files!? I'll find a way to apply a patch with a diff soon: https://1drv.ms/u/s!AgAdDsqhqeAPhmrr2HRwvZ2dS12n?e=zoAmR7
> 
> Thanks for your patience with the munted build system and if you'd like to see it fixed we're always keen on pull requests.
> 
> * Aaron.

Hi Aaron,

It turns out I don't need the main.pak, because I just ended up unpacking it using a Plants vs. Zombies main.pak Patcher, and placed all the folders the game asked for in the files. But thanks anyway!
