### ISSUE TITLE
I cant build with visual studio 2019, error in class board

### ISSUE THREAD

**Issue by khotaonickvai** [Patoke/re-plants-vs-zombies#5]
i cant build with visual studio 2019, i get the error with unreachable(); function in board class 
![bug](https://github.com/Patoke/re-plants-vs-zombies/assets/49309014/604a2948-1c6b-4fb2-a234-840ecd9a8618)
![bug](https://github.com/Patoke/re-plants-vs-zombies/assets/49309014/6c6eda07-351c-4486-aa17-b85740323637)

**Comment by Patoke** [comment]
Hello, I hope you're having a great day.

That error is happening because of our implementation of unreachable which uses std::unreachable from the c++23 standard, to fix it just go to the macro definition and remove its function calls, such so as it just ends up being `#define unreachable`
We're going to try and find a way to make it compilable for older versions of the c++ standard but for now it's c++23 only (which is not present in visual studio 2019)

I hope this fixes your issue.
Best regards, Patoke.

**Comment by minerscale** [comment]
You might be able to replace the definition of `std::unreachable()` with `abort()`. That could be a bit more portable. Although I'm not sure how the compiler complains.

**Comment by khotaonickvai** [comment]
> Hello, I hope you're having a great day.
> 
> That error is happening because of our implementation of unreachable which uses std::unreachable from the c++23 standard, to fix it just go to the macro definition and remove its function calls, such so as it just ends up being `#define unreachable` We're going to try and find a way to make it compilable for older versions of the c++ standard but for now it's c++23 only (which is not present in visual studio 2019)
> 
> I hope this fixes your issue. Best regards, Patoke.

thank you and i resolve that by use for define :

#ifdef __GNUC__ // GCC 4.8+, Clang, Intel and other compilers compatible with GCC (-std=c++0x or above)
[[noreturn]] inline __attribute__((always_inline)) void unreachable() { __builtin_unreachable(); }
#elif defined(_MSC_VER) // MSVC
[[noreturn]] __forceinline void unreachable() { __assume(false); }
#else // ???
inline void unreachable() {}
#endif

i built finish with VS2019 newest version.
thank you
